name: Feature request
description: Propose a product improvement
title: "[Feature]: "
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: Customer problem
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed outcome
    validations:
      required: true
  - type: textarea
    attributes:
      label: Acceptance criteria
